// Lingue supportate da Google Translate (target della traduzione).
// code = codice ISO usato da Google; name = nome nativo per l'utente.
export const TRANSLATE_LANGS = [
  { code: "af", name: "Afrikaans" },
  { code: "sq", name: "Shqip (Albanese)" },
  { code: "am", name: "አማርኛ (Amarico)" },
  { code: "ar", name: "العربية (Arabo)" },
  { code: "hy", name: "Հայերեն (Armeno)" },
  { code: "az", name: "Azərbaycan" },
  { code: "eu", name: "Euskara (Basco)" },
  { code: "be", name: "Беларуская" },
  { code: "bn", name: "বাংলা (Bengalese)" },
  { code: "bs", name: "Bosanski" },
  { code: "bg", name: "Български (Bulgaro)" },
  { code: "ca", name: "Català (Catalano)" },
  { code: "ceb", name: "Cebuano" },
  { code: "zh-CN", name: "中文 简体 (Cinese sempl.)" },
  { code: "zh-TW", name: "中文 繁體 (Cinese trad.)" },
  { code: "co", name: "Corsu (Còrso)" },
  { code: "hr", name: "Hrvatski (Croato)" },
  { code: "cs", name: "Čeština (Ceco)" },
  { code: "da", name: "Dansk (Danese)" },
  { code: "nl", name: "Nederlands (Olandese)" },
  { code: "en", name: "English (Inglese)" },
  { code: "eo", name: "Esperanto" },
  { code: "et", name: "Eesti (Estone)" },
  { code: "fi", name: "Suomi (Finlandese)" },
  { code: "fr", name: "Français (Francese)" },
  { code: "fy", name: "Frysk (Frisone)" },
  { code: "gl", name: "Galego (Galiziano)" },
  { code: "ka", name: "ქართული (Georgiano)" },
  { code: "de", name: "Deutsch (Tedesco)" },
  { code: "el", name: "Ελληνικά (Greco)" },
  { code: "gu", name: "ગુજરાતી" },
  { code: "ht", name: "Kreyòl Ayisyen" },
  { code: "ha", name: "Hausa" },
  { code: "haw", name: "ʻŌlelo Hawaiʻi" },
  { code: "he", name: "עברית (Ebraico)" },
  { code: "hi", name: "हिन्दी (Hindi)" },
  { code: "hmn", name: "Hmong" },
  { code: "hu", name: "Magyar (Ungherese)" },
  { code: "is", name: "Íslenska (Islandese)" },
  { code: "ig", name: "Igbo" },
  { code: "id", name: "Indonesia" },
  { code: "ga", name: "Gaeilge (Irlandese)" },
  { code: "it", name: "Italiano" },
  { code: "ja", name: "日本語 (Giapponese)" },
  { code: "jw", name: "Basa Jawa" },
  { code: "kn", name: "ಕನ್ನಡ (Kannada)" },
  { code: "kk", name: "Қазақ (Kazako)" },
  { code: "km", name: "ខ្មែរ (Khmer)" },
  { code: "rw", name: "Kinyarwanda" },
  { code: "ko", name: "한국어 (Coreano)" },
  { code: "ku", name: "Kurdî (Curdo)" },
  { code: "ky", name: "Кыргызча" },
  { code: "lo", name: "ລາວ (Lao)" },
  { code: "la", name: "Latina (Latino)" },
  { code: "lv", name: "Latviešu (Lettone)" },
  { code: "lt", name: "Lietuvių (Lituano)" },
  { code: "lb", name: "Lëtzebuergesch" },
  { code: "mk", name: "Македонски" },
  { code: "mg", name: "Malagasy" },
  { code: "ms", name: "Bahasa Melayu" },
  { code: "ml", name: "മലയാളം (Malayalam)" },
  { code: "mt", name: "Malti (Maltese)" },
  { code: "mi", name: "Māori" },
  { code: "mr", name: "मराठी (Marathi)" },
  { code: "mn", name: "Монгол (Mongolo)" },
  { code: "my", name: "မြန်မာ (Birmano)" },
  { code: "ne", name: "नेपाली (Nepalese)" },
  { code: "no", name: "Norsk (Norvegese)" },
  { code: "ny", name: "Chichewa" },
  { code: "or", name: "ଓଡ଼ିଆ (Odia)" },
  { code: "ps", name: "پښتو (Pashto)" },
  { code: "fa", name: "فارسی (Persiano)" },
  { code: "pl", name: "Polski (Polacco)" },
  { code: "pt", name: "Português (Portoghese)" },
  { code: "pa", name: "ਪੰਜਾਬੀ (Punjabi)" },
  { code: "ro", name: "Română (Rumeno)" },
  { code: "ru", name: "Русский (Russo)" },
  { code: "sm", name: "Samoan" },
  { code: "gd", name: "Gàidhlig (Gaelico scoz.)" },
  { code: "sr", name: "Српски (Serbo)" },
  { code: "st", name: "Sesotho" },
  { code: "sn", name: "Shona" },
  { code: "sd", name: "سنڌي (Sindhi)" },
  { code: "si", name: "සිංහල (Singalese)" },
  { code: "sk", name: "Slovenčina (Slovacco)" },
  { code: "sl", name: "Slovenščina (Sloveno)" },
  { code: "so", name: "Soomaali (Somalo)" },
  { code: "es", name: "Español (Spagnolo)" },
  { code: "su", name: "Basa Sunda" },
  { code: "sw", name: "Kiswahili (Swahili)" },
  { code: "sv", name: "Svenska (Svedese)" },
  { code: "tl", name: "Tagalog (Filippino)" },
  { code: "tg", name: "Тоҷикӣ (Tagiko)" },
  { code: "ta", name: "தமிழ் (Tamil)" },
  { code: "tt", name: "Татарча (Tataro)" },
  { code: "te", name: "తెలుగు (Telugu)" },
  { code: "th", name: "ไทย (Thailandese)" },
  { code: "tr", name: "Türkçe (Turco)" },
  { code: "tk", name: "Türkmen (Turkmeno)" },
  { code: "uk", name: "Українська (Ucraino)" },
  { code: "ur", name: "اردو (Urdu)" },
  { code: "ug", name: "ئۇيغۇرچە (Uiguro)" },
  { code: "uz", name: "Oʻzbek (Uzbeko)" },
  { code: "vi", name: "Tiếng Việt (Vietnamita)" },
  { code: "cy", name: "Cymraeg (Gallese)" },
  { code: "xh", name: "isiXhosa" },
  { code: "yi", name: "ייִדיש (Yiddish)" },
  { code: "yo", name: "Yorùbá" },
  { code: "zu", name: "isiZulu" },
];

export function langName(code) {
  if (!code) return null;
  const f = TRANSLATE_LANGS.find((l) => l.code === code);
  return f ? f.name : code.toUpperCase();
}
