// Ignorati · QR di invito · verifica reciproca — nelle 12 lingue.
const L = ["it", "en", "zh", "hi", "es", "pt", "ar", "fr", "ru", "de", "ja", "tr"];
const K = {
  "blk.title": ["Contatti ignorati", "Ignored contacts", "已忽略的联系人", "अनदेखा किए संपर्क", "Contactos ignorados", "Contatos ignorados", "جهات الاتصال المتجاهلة", "Contacts ignorés", "Игнорируемые контакты", "Ignorierte Kontakte", "無視した連絡先", "Yoksayılan kişiler"],
  "blk.hint": ["Chi hai ignorato non può scriverti né chiamarti. Sbloccalo per tornare a riceverlo.", "People you ignored cannot write or call you. Unblock to hear from them again.", "被忽略的人无法给你发消息或打电话。解除屏蔽即可恢复。", "अनदेखा किए लोग आपको संदेश या कॉल नहीं कर सकते. फिर से पाने के लिए अनब्लॉक करें.", "Quien has ignorado no puede escribirte ni llamarte. Desbloquéalo para volver a recibirlo.", "Quem você ignorou não pode escrever nem ligar. Desbloqueie para voltar a receber.", "من تتجاهله لا يمكنه مراسلتك أو الاتصال بك. أزل الحظر لتستقبله مجددًا.", "Les personnes ignorées ne peuvent ni vous écrire ni vous appeler. Débloquez pour les recevoir à nouveau.", "Игнорируемые не могут писать и звонить вам. Разблокируйте, чтобы снова получать сообщения.", "Ignorierte Personen können dir nicht schreiben oder anrufen. Entsperre sie, um sie wieder zu empfangen.", "無視した相手はあなたにメッセージも通話もできません。解除すると再び受け取れます。", "Yoksaydığın kişiler sana yazamaz ve arayamaz. Engeli kaldırınca yeniden alırsın."],
  "blk.empty": ["Nessun contatto ignorato.", "No ignored contacts.", "没有已忽略的联系人。", "कोई अनदेखा संपर्क नहीं.", "Ningún contacto ignorado.", "Nenhum contato ignorado.", "لا توجد جهات اتصال متجاهلة.", "Aucun contact ignoré.", "Игнорируемых контактов нет.", "Keine ignorierten Kontakte.", "無視した連絡先はありません。", "Yoksayılan kişi yok."],
  "blk.unblock": ["Sblocca", "Unblock", "解除屏蔽", "अनब्लॉक", "Desbloquear", "Desbloquear", "إزالة الحظر", "Débloquer", "Разблокировать", "Entsperren", "解除", "Engeli kaldır"],
  "blk.blindNote": ["I blocchi della rubrica cieca restano anonimi: il server non sa chi sono e non compaiono qui.", "Blind address book blocks stay anonymous: the server does not know who they are, so they are not listed here.", "盲通讯录中的屏蔽保持匿名：服务器不知道对象是谁，因此不会显示在此。", "ब्लाइंड रूब्रिका के ब्लॉक गुमनाम रहते हैं: सर्वर नहीं जानता कि वे कौन हैं, इसलिए यहाँ नहीं दिखते.", "Los bloqueos de la agenda ciega son anónimos: el servidor no sabe quiénes son y no aparecen aquí.", "Os bloqueios da agenda cega são anônimos: o servidor não sabe quem são e não aparecem aqui.", "الحظر في الدفتر الأعمى يبقى مجهولاً: الخادم لا يعرف هويتهم ولا يظهرون هنا.", "Les blocages du carnet aveugle restent anonymes : le serveur ignore de qui il s'agit, ils n'apparaissent pas ici.", "Блокировки «слепой» книги контактов анонимны: сервер не знает, кто это, поэтому их здесь нет.", "Sperren im blinden Adressbuch bleiben anonym: der Server weiß nicht, wer sie sind, daher stehen sie nicht hier.", "ブラインドアドレス帳のブロックは匿名のままです。サーバーは相手を知らないため、ここには表示されません。", "Kör rehberdeki engeller anonim kalır: sunucu kim olduklarını bilmez, bu yüzden burada görünmezler."],
  "qr.mine": ["Il mio QR", "My QR", "我的二维码", "मेरा QR", "Mi QR", "Meu QR", "رمزي", "Mon QR", "Мой QR", "Mein QR", "自分のQR", "QR kodum"],
  "qr.mineHint": ["Fai inquadrare questo codice: contiene il tuo indirizzo e l'impronta delle tue chiavi.", "Let them scan this code: it carries your address and your key fingerprint.", "让对方扫描这个码：其中包含你的地址和密钥指纹。", "इसे स्कैन करने दें: इसमें आपका पता और कुंजी फिंगरप्रिंट है.", "Haz que escaneen este código: contiene tu dirección y la huella de tus claves.", "Deixe escanearem este código: contém seu endereço e a impressão das suas chaves.", "دعهم يمسحون هذا الرمز: يحتوي على عنوانك وبصمة مفاتيحك.", "Faites scanner ce code : il contient votre adresse et l'empreinte de vos clés.", "Дайте отсканировать этот код: в нём ваш адрес и отпечаток ваших ключей.", "Lass diesen Code scannen: er enthält deine Adresse und den Fingerprint deiner Schlüssel.", "このコードを読み取ってもらいます。あなたのアドレスと鍵の指紋が含まれます。", "Bu kodu okutun: adresinizi ve anahtar parmak izinizi taşır."],
  "qr.scan": ["Inquadra il suo QR", "Scan their QR", "扫描对方的二维码", "उनका QR स्कैन करें", "Escanea su QR", "Escaneie o QR dele", "امسح رمزه", "Scanner son QR", "Сканировать его QR", "Seinen QR scannen", "相手のQRを読み取る", "Onun QR'ını okut"],
  "qr.scanHint": ["Aggiunge il contatto e lo segna verificato in un colpo.", "Adds the contact and marks it verified in one go.", "一次性添加联系人并标记为已验证。", "संपर्क जोड़ता है और एक ही बार में सत्यापित कर देता है.", "Añade el contacto y lo marca verificado de una vez.", "Adiciona o contato e o marca verificado de uma vez.", "يضيف جهة الاتصال ويعلّمها موثّقة في خطوة واحدة.", "Ajoute le contact et le marque vérifié d'un coup.", "Добавляет контакт и сразу помечает его проверенным.", "Fügt den Kontakt hinzu und markiert ihn sofort als verifiziert.", "連絡先を追加し、同時に検証済みにします。", "Kişiyi ekler ve tek seferde doğrulanmış işaretler."],
  "qr.paste": ["Incolla il codice", "Paste the code", "粘贴代码", "कोड पेस्ट करें", "Pega el código", "Cole o código", "الصق الرمز", "Coller le code", "Вставить код", "Code einfügen", "コードを貼り付け", "Kodu yapıştır"],
  "qr.upload": ["Carica la foto del QR", "Upload a photo of the QR", "上传二维码照片", "QR की फोटो अपलोड करें", "Sube la foto del QR", "Envie a foto do QR", "ارفع صورة الرمز", "Charger la photo du QR", "Загрузить фото QR", "Foto des QR laden", "QRの写真を読み込む", "QR fotoğrafını yükle"],
  "qr.check": ["Controlla", "Check", "检查", "जाँचें", "Comprobar", "Verificar", "تحقق", "Vérifier", "Проверить", "Prüfen", "確認", "Kontrol et"],
  "qr.added": ["{name} aggiunto e verificato.", "{name} added and verified.", "已添加并验证 {name}。", "{name} जोड़ा और सत्यापित किया गया.", "{name} añadido y verificado.", "{name} adicionado e verificado.", "تمت إضافة {name} والتحقق منه.", "{name} ajouté et vérifié.", "{name} добавлен и проверен.", "{name} hinzugefügt und verifiziert.", "{name} を追加し検証しました。", "{name} eklendi ve doğrulandı."],
  "qr.addedUnverified": ["{name} aggiunto, ma l'impronta non combacia: confrontate il numero di sicurezza a voce.", "{name} added, but the fingerprint does not match: compare the safety number out loud.", "已添加 {name}，但指纹不匹配：请口头核对安全号码。", "{name} जोड़ा गया, पर फिंगरप्रिंट मेल नहीं खाता: सुरक्षा नंबर बोलकर मिलाएँ.", "{name} añadido, pero la huella no coincide: comparad el número de seguridad en voz alta.", "{name} adicionado, mas a impressão não coincide: confiram o número de segurança em voz alta.", "تمت إضافة {name}، لكن البصمة غير مطابقة: قارنا رقم الأمان شفهيًا.", "{name} ajouté, mais l'empreinte ne correspond pas : comparez le numéro de sécurité à voix haute.", "{name} добавлен, но отпечаток не совпадает: сверьте код безопасности голосом.", "{name} hinzugefügt, aber der Fingerprint passt nicht: vergleicht die Sicherheitsnummer laut.", "{name} を追加しましたが指紋が一致しません。安全番号を声に出して照合してください。", "{name} eklendi ama parmak izi uyuşmuyor: güvenlik numarasını sesli karşılaştırın."],
  "qr.self": ["Questo è il tuo codice.", "This is your own code.", "这是你自己的码。", "यह आपका ही कोड है.", "Este es tu propio código.", "Este é o seu próprio código.", "هذا رمزك الخاص.", "C'est votre propre code.", "Это ваш собственный код.", "Das ist dein eigener Code.", "これはあなた自身のコードです。", "Bu senin kendi kodun."],
  "qr.bad": ["Codice non riconosciuto.", "Code not recognised.", "无法识别该码。", "कोड पहचाना नहीं गया.", "Código no reconocido.", "Código não reconhecido.", "الرمز غير معروف.", "Code non reconnu.", "Код не распознан.", "Code nicht erkannt.", "コードを認識できません。", "Kod tanınmadı."],
  "vfy.title": ["Verifica contatto", "Verify contact", "验证联系人", "संपर्क सत्यापन", "Verificar contacto", "Verificar contato", "التحقق من جهة الاتصال", "Vérifier le contact", "Проверка контакта", "Kontakt verifizieren", "連絡先の検証", "Kişiyi doğrula"],
  "vfy.hint": ["Confrontate a voce le 60 cifre: se combaciano su entrambi gli schermi, nessuno si è messo in mezzo.", "Read the 60 digits out loud: if they match on both screens, nobody is in the middle.", "口头核对这 60 位数字：两边屏幕一致就没有人在中间。", "60 अंक बोलकर मिलाएँ: दोनों स्क्रीन पर समान हों तो बीच में कोई नहीं है.", "Comparad los 60 dígitos en voz alta: si coinciden en ambas pantallas, nadie está en medio.", "Comparem os 60 dígitos em voz alta: se coincidem nas duas telas, ninguém está no meio.", "اقرأا الأرقام الستين بصوت عالٍ: إن تطابقت على الشاشتين فلا أحد في المنتصف.", "Comparez les 60 chiffres à voix haute : s'ils correspondent sur les deux écrans, personne n'est au milieu.", "Сверьте 60 цифр голосом: если совпадают на обоих экранах — посредника нет.", "Vergleicht die 60 Ziffern laut: stimmen sie auf beiden Bildschirmen, ist niemand dazwischen.", "60桁を声に出して照合します。両方の画面で一致すれば、間に誰もいません。", "60 haneyi sesli karşılaştırın: iki ekranda aynıysa arada kimse yok."],
  "vfy.number": ["Numero di sicurezza", "Safety number", "安全号码", "सुरक्षा नंबर", "Número de seguridad", "Número de segurança", "رقم الأمان", "Numéro de sécurité", "Код безопасности", "Sicherheitsnummer", "安全番号", "Güvenlik numarası"],
  "vfy.mark": ["Ho confrontato: è corretto", "I compared it: it matches", "已核对：一致", "मैंने मिलाया: सही है", "Lo he comparado: coincide", "Comparei: está correto", "قارنته: مطابق", "J'ai comparé : ça correspond", "Сверил: совпадает", "Verglichen: stimmt", "照合しました：一致します", "Karşılaştırdım: doğru"],
  "vfy.done": ["Verificato", "Verified", "已验证", "सत्यापित", "Verificado", "Verificado", "موثّق", "Vérifié", "Проверено", "Verifiziert", "検証済み", "Doğrulandı"],
  "vfy.changed": ["Le chiavi sono cambiate dopo la verifica: rifatela.", "The keys changed after verification: do it again.", "验证后密钥已更改：请重新验证。", "सत्यापन के बाद कुंजियाँ बदल गईं: फिर से करें.", "Las claves han cambiado tras la verificación: repítela.", "As chaves mudaram após a verificação: repita.", "تغيّرت المفاتيح بعد التحقق: أعيدا العملية.", "Les clés ont changé après la vérification : refaites-la.", "Ключи изменились после проверки: повторите её.", "Die Schlüssel haben sich nach der Verifizierung geändert: wiederhole sie.", "検証後に鍵が変わりました。もう一度検証してください。", "Doğrulamadan sonra anahtarlar değişti: tekrar yapın."],
  "vfy.now": ["Verifica ora", "Verify now", "立即验证", "अब सत्यापित करें", "Verificar ahora", "Verificar agora", "تحقق الآن", "Vérifier maintenant", "Проверить сейчас", "Jetzt verifizieren", "今すぐ検証", "Şimdi doğrula"],
  "vfy.later": ["Più tardi", "Later", "稍后", "बाद में", "Más tarde", "Mais tarde", "لاحقًا", "Plus tard", "Позже", "Später", "あとで", "Sonra"],
  "vfy.askBody": ["Richiesta accettata. Volete essere certi che nessuno si sia messo in mezzo? Confrontate il numero di sicurezza con {name}.", "Request accepted. Want to be sure nobody is in the middle? Compare the safety number with {name}.", "已接受请求。想确认没有人在中间？与 {name} 核对安全号码。", "अनुरोध स्वीकार. पक्का करना है कि बीच में कोई नहीं? {name} के साथ सुरक्षा नंबर मिलाएँ.", "Solicitud aceptada. ¿Quieres asegurarte de que nadie está en medio? Compara el número de seguridad con {name}.", "Solicitação aceita. Quer garantir que ninguém está no meio? Compare o número de segurança com {name}.", "تم قبول الطلب. تريد التأكد أن لا أحد في المنتصف؟ قارن رقم الأمان مع {name}.", "Demande acceptée. Vous voulez être sûr que personne n'est au milieu ? Comparez le numéro de sécurité avec {name}.", "Запрос принят. Хотите убедиться, что посредника нет? Сверьте код безопасности с {name}.", "Anfrage angenommen. Sicher sein, dass niemand dazwischen ist? Vergleiche die Sicherheitsnummer mit {name}.", "リクエストを承認しました。間に誰もいないと確認しますか？{name} と安全番号を照合してください。", "İstek kabul edildi. Arada kimse olmadığından emin olmak ister misin? {name} ile güvenlik numarasını karşılaştır."],
  "vfy.wait": ["Attendo le chiavi…", "Waiting for the keys…", "正在等待密钥…", "कुंजियों की प्रतीक्षा…", "Esperando las claves…", "Aguardando as chaves…", "في انتظار المفاتيح…", "En attente des clés…", "Ожидание ключей…", "Warte auf die Schlüssel…", "鍵を待っています…", "Anahtarlar bekleniyor…"],
  "req.notifTitle": ["Nuova richiesta di contatto", "New contact request", "新的联系人请求", "नया संपर्क अनुरोध", "Nueva solicitud de contacto", "Nova solicitação de contato", "طلب جهة اتصال جديد", "Nouvelle demande de contact", "Новый запрос контакта", "Neue Kontaktanfrage", "新しい連絡先リクエスト", "Yeni kişi isteği"],
  "req.notifBody": ["{name} ti ha aggiunto in rubrica: accetta per potervi scrivere.", "{name} added you: accept to be able to write to each other.", "{name} 已添加你：接受后即可互相发消息。", "{name} ने आपको जोड़ा: स्वीकारें ताकि एक-दूसरे को लिख सकें.", "{name} te ha añadido: acepta para poder escribiros.", "{name} te adicionou: aceite para poderem se escrever.", "أضافك {name}: اقبل لتتمكنا من التراسل.", "{name} vous a ajouté : acceptez pour pouvoir vous écrire.", "{name} добавил вас: примите, чтобы писать друг другу.", "{name} hat dich hinzugefügt: nimm an, um euch schreiben zu können.", "{name} さんがあなたを追加しました。承認すると相互に送信できます。", "{name} seni ekledi: yazışabilmek için kabul et."],
};
export const REQ12B = (() => {
  const out = {};
  L.forEach((c, i) => { const p = {}; Object.keys(K).forEach((k) => { p[k] = K[k][i] || K[k][0]; }); out[c] = p; });
  return out;
})();
