// CHIAMATE, COSTELLAZIONE E FORZA DEL PIN NELLE 12 LINGUE — v2.9.3.
// Ultimi tre pezzi della web app scritti a mano in italiano/inglese dentro il JSX.
// Le unità di tempo hanno due forme (una, molte): dove una lingua non le distingue la
// forma è ripetuta, dove il russo vuole il genitivo plurale ("2,5 лет") è già così.
const L = ["it", "en", "zh", "hi", "es", "pt", "ar", "fr", "ru", "de", "ja", "tr"];

const K = {
  // ── chiamate ──
  "call.mic.denied": ["Accesso al microfono negato. Concedilo nel browser e riprova.", "Microphone access denied. Allow it in the browser and try again.", "麦克风权限被拒绝。请在浏览器中允许后重试。", "माइक्रोफ़ोन की अनुमति नहीं मिली। ब्राउज़र में अनुमति दें और फिर आज़माएँ।", "Acceso al micrófono denegado. Concédelo en el navegador y vuelve a intentarlo.", "Acesso ao microfone negado. Permita no navegador e tente de novo.", "تم رفض الوصول إلى الميكروفون. اسمح به في المتصفح ثم أعد المحاولة.", "Accès au microphone refusé. Autorisez-le dans le navigateur et réessayez.", "Доступ к микрофону запрещён. Разрешите его в браузере и попробуйте снова.", "Mikrofonzugriff verweigert. Erlaube ihn im Browser und versuche es erneut.", "マイクへのアクセスが拒否されました。ブラウザーで許可してからやり直してください。", "Mikrofon erişimi reddedildi. Tarayıcıda izin ver ve yeniden dene."],
  "call.mic.none": ["Nessun microfono trovato su questo dispositivo.", "No microphone found on this device.", "此设备上找不到麦克风。", "इस डिवाइस पर कोई माइक्रोफ़ोन नहीं मिला।", "No se ha encontrado ningún micrófono en este dispositivo.", "Nenhum microfone encontrado neste dispositivo.", "لا يوجد ميكروفون على هذا الجهاز.", "Aucun microphone trouvé sur cet appareil.", "На этом устройстве микрофон не найден.", "Auf diesem Gerät wurde kein Mikrofon gefunden.", "この端末にマイクが見つかりません。", "Bu cihazda mikrofon bulunamadı."],
  "call.mic.busy": ["Il microfono è occupato da un'altra applicazione.", "The microphone is busy in another application.", "麦克风正被其他应用占用。", "माइक्रोफ़ोन किसी दूसरे ऐप में व्यस्त है।", "El micrófono está ocupado por otra aplicación.", "O microfone está ocupado por outro aplicativo.", "الميكروفون مشغول في تطبيق آخر.", "Le microphone est utilisé par une autre application.", "Микрофон занят другим приложением.", "Das Mikrofon wird von einer anderen Anwendung benutzt.", "マイクは別のアプリが使用中です。", "Mikrofon başka bir uygulamada kullanılıyor."],
  "call.nokeyfile": ["File chiave non caricato in questa scheda.", "Keyfile not loaded in this tab.", "此标签页未加载密钥文件。", "इस टैब में कीफ़ाइल लोड नहीं है।", "El archivo de clave no está cargado en esta pestaña.", "Arquivo de chave não carregado nesta aba.", "ملف المفتاح غير محمَّل في هذه التبويبة.", "Fichier de clé non chargé dans cet onglet.", "Файл ключа не загружен в этой вкладке.", "Schlüsseldatei in diesem Tab nicht geladen.", "このタブには鍵ファイルが読み込まれていません。", "Bu sekmede anahtar dosyası yüklü değil."],
  "call.notready": ["Il destinatario non ha ancora attivato le chiamate.", "Recipient has not activated calls yet.", "对方尚未启用通话。", "प्राप्तकर्ता ने अभी कॉल चालू नहीं की हैं।", "El destinatario aún no ha activado las llamadas.", "O destinatário ainda não ativou as chamadas.", "لم يفعّل المستلم المكالمات بعد.", "Le destinataire n'a pas encore activé les appels.", "Получатель ещё не включил звонки.", "Der Empfänger hat Anrufe noch nicht aktiviert.", "相手はまだ通話を有効にしていません。", "Alıcı aramaları henüz etkinleştirmedi."],
  "call.noanswer": ["Nessuna risposta.", "No answer.", "无人应答。", "कोई जवाब नहीं।", "Sin respuesta.", "Sem resposta.", "لا مجيب.", "Pas de réponse.", "Нет ответа.", "Keine Antwort.", "応答がありません。", "Yanıt yok."],
  "call.calling": ["sto chiamando…", "calling…", "正在呼叫…", "कॉल हो रही है…", "llamando…", "chamando…", "جارٍ الاتصال…", "appel en cours…", "вызов…", "rufe an…", "発信中…", "aranıyor…"],
  "call.ringing": ["chiamata in arrivo", "incoming call", "来电", "आ रही कॉल", "llamada entrante", "chamada recebida", "مكالمة واردة", "appel entrant", "входящий вызов", "eingehender Anruf", "着信中", "gelen arama"],
  "call.connected": ["in corso · solo audio", "connected · audio only", "通话中 · 仅语音", "जुड़ा · केवल ऑडियो", "en curso · solo audio", "em curso · só áudio", "جارية · صوت فقط", "en cours · audio seulement", "идёт · только звук", "verbunden · nur Ton", "通話中 · 音声のみ", "bağlı · yalnızca sesli"],
  "call.failed": ["non riuscita", "failed", "失败", "असफल", "fallida", "falhou", "فشلت", "échec", "не удалось", "fehlgeschlagen", "失敗", "başarısız"],
  "call.verified": ["firma verificata", "signature verified", "签名已验证", "हस्ताक्षर सत्यापित", "firma verificada", "assinatura verificada", "تم التحقق من التوقيع", "signature vérifiée", "подпись проверена", "Signatur geprüft", "署名を検証済み", "imza doğrulandı"],
  "call.unsigned": ["firma assente", "unsigned", "无签名", "हस्ताक्षर नहीं", "sin firma", "sem assinatura", "بلا توقيع", "non signé", "без подписи", "ohne Signatur", "署名なし", "imzasız"],
  "call.sasHint": ["Leggetele a voce: devono coincidere", "Read these aloud: they must match", "念出来对一下：必须一致", "इन्हें बोलकर मिलाएँ: एक जैसे होने चाहिए", "Leedlas en voz alta: deben coincidir", "Leiam em voz alta: devem coincidir", "اقرأوها بصوت عالٍ: يجب أن تتطابق", "Lisez-les à voix haute : elles doivent correspondre", "Прочитайте вслух: должны совпасть", "Laut vorlesen: sie müssen übereinstimmen", "声に出して読み合わせてください。一致するはずです", "Sesli okuyun: aynı olmalı"],
  "call.answer": ["rispondi", "answer", "接听", "उत्तर दें", "responder", "atender", "أجب", "répondre", "ответить", "annehmen", "応答", "yanıtla"],
  "call.decline": ["rifiuta", "decline", "拒绝", "अस्वीकार", "rechazar", "recusar", "ارفض", "refuser", "отклонить", "ablehnen", "拒否", "reddet"],
  "call.mute": ["muto", "mute", "静音", "म्यूट", "silenciar", "silenciar", "كتم", "couper le micro", "выключить микрофон", "stumm", "ミュート", "sustur"],
  "call.unmute": ["riattiva", "unmute", "取消静音", "अनम्यूट", "reactivar", "reativar", "إلغاء الكتم", "réactiver le micro", "включить микрофон", "Ton an", "ミュート解除", "sesi aç"],
  "call.hangup": ["chiudi", "hang up", "挂断", "काटें", "colgar", "encerrar", "إنهاء", "raccrocher", "завершить", "auflegen", "通話終了", "kapat"],
  "call.footer": ["solo voce · media via TURN sovrano", "voice only · media via sovereign TURN", "仅语音 · 媒体经自有 TURN", "केवल आवाज़ · मीडिया अपने TURN से", "solo voz · medios vía TURN soberano", "só voz · mídia via TURN soberano", "صوت فقط · الوسائط عبر TURN سيادي", "voix seule · média via TURN souverain", "только голос · медиа через свой TURN", "nur Stimme · Medien über eigenen TURN", "音声のみ · メディアは自前の TURN 経由", "yalnızca ses · medya kendi TURN üzerinden"],

  // ── costellazione ──
  "mesh.title": ["Costellazione", "Constellation", "星座图", "नक्षत्र", "Constelación", "Constelação", "الكوكبة", "Constellation", "Созвездие", "Konstellation", "星座", "Takımyıldız"],
  "mesh.sub": ["La rete adesso: validatori del consenso, relay del mixnet e Nodi Sovrani.", "The network as it is right now: consensus validators, mixnet relays and Sovereign Nodes.", "此刻的网络：共识验证者、混淆网络中继与自主节点。", "अभी का नेटवर्क: सहमति सत्यापक, मिक्सनेट रिले और सॉवरेन नोड।", "La red ahora mismo: validadores del consenso, relays del mixnet y Nodos Soberanos.", "A rede agora: validadores do consenso, relays do mixnet e Nós Soberanos.", "الشبكة الآن: مدققو التوافق ومرحّلات شبكة الخلط والعُقد السيادية.", "Le réseau à l'instant : validateurs du consensus, relais du mixnet et Nœuds Souverains.", "Сеть прямо сейчас: валидаторы консенсуса, реле микснета и Суверенные узлы.", "Das Netz genau jetzt: Konsens-Validatoren, Mixnet-Relays und Souveräne Knoten.", "いまのネットワーク：合意のバリデータ、ミックスネットのリレー、ソブリンノード。", "Ağın şu anki hâli: konsensüs doğrulayıcıları, mixnet röleleri ve Egemen Düğümler."],
  "mesh.becomeNode": ["Diventa Nodo Sovrano", "Become a Sovereign Node", "成为自主节点", "सॉवरेन नोड बनें", "Conviértete en Nodo Soberano", "Torne-se um Nó Soberano", "كن عقدة سيادية", "Devenez un Nœud Souverain", "Стать Суверенным узлом", "Werde ein Souveräner Knoten", "ソブリンノードになる", "Egemen Düğüm ol"],
  "mesh.validators": ["validatori", "validators", "验证者", "सत्यापक", "validadores", "validadores", "المدققون", "validateurs", "валидаторы", "Validatoren", "バリデータ", "doğrulayıcılar"],
  "mesh.relays": ["relay", "relays", "中继", "रिले", "relays", "relays", "المرحّلات", "relais", "реле", "Relays", "リレー", "röleler"],
  "mesh.nodes": ["nodi sovrani", "sovereign nodes", "自主节点", "सॉवरेन नोड", "nodos soberanos", "nós soberanos", "العقد السيادية", "nœuds souverains", "суверенные узлы", "souveräne Knoten", "ソブリンノード", "egemen düğümler"],
  "mesh.quorum": ["quorum", "quorum", "法定人数", "कोरम", "quórum", "quórum", "النصاب", "quorum", "кворум", "Quorum", "定足数", "yeterlilik"],
  "mesh.healthy": ["integro", "healthy", "健康", "स्वस्थ", "íntegro", "íntegro", "سليم", "sain", "в норме", "gesund", "健全", "sağlıklı"],
  "mesh.atRisk": ["a rischio", "at risk", "有风险", "जोखिम में", "en riesgo", "em risco", "في خطر", "à risque", "под угрозой", "gefährdet", "危険", "risk altında"],
  "mesh.silent": ["nessun nodo sta rispondendo", "no node is reporting", "没有节点在上报", "कोई नोड जवाब नहीं दे रहा", "ningún nodo está respondiendo", "nenhum nó está respondendo", "لا توجد عقدة تُبلّغ", "aucun nœud ne répond", "ни один узел не отвечает", "kein Knoten meldet sich", "応答しているノードがありません", "hiçbir düğüm bildirim yapmıyor"],
  "mesh.legend.validator": ["validatore del consenso", "consensus validator", "共识验证者", "सहमति सत्यापक", "validador del consenso", "validador do consenso", "مدقق التوافق", "validateur du consensus", "валидатор консенсуса", "Konsens-Validator", "合意のバリデータ", "konsensüs doğrulayıcısı"],
  "mesh.legend.relay": ["relay del mixnet", "mixnet relay", "混淆网络中继", "मिक्सनेट रिले", "relay del mixnet", "relay do mixnet", "مرحّل شبكة الخلط", "relais du mixnet", "реле микснета", "Mixnet-Relay", "ミックスネットのリレー", "mixnet rölesi"],
  "mesh.legend.sovereign": ["nodo sovrano", "sovereign node", "自主节点", "सॉवरेन नोड", "nodo soberano", "nó soberano", "عقدة سيادية", "nœud souverain", "суверенный узел", "souveräner Knoten", "ソブリンノード", "egemen düğüm"],
  "mesh.signed": ["firmati", "signed", "已签名", "हस्ताक्षरित", "firmados", "assinados", "موقّعة", "signés", "подписано", "signiert", "署名済み", "imzalı"],
  "mesh.unknownRegion": ["regione ignota", "unknown region", "地区未知", "अज्ञात क्षेत्र", "región desconocida", "região desconhecida", "منطقة غير معروفة", "région inconnue", "регион неизвестен", "unbekannte Region", "地域不明", "bölge bilinmiyor"],
  "mesh.relayed": ["inoltrati", "relayed", "已转发", "अग्रेषित", "reenviados", "repassados", "مُرحَّلة", "relayés", "переслано", "weitergeleitet", "中継済み", "iletildi"],

  // ── forza del PIN ──
  "pin.time": ["tempo per indovinarlo", "time to crack", "破解所需时间", "अनुमान लगाने का समय", "tiempo para adivinarlo", "tempo para descobrir", "زمن التخمين", "temps pour le casser", "время на подбор", "Zeit zum Knacken", "推測にかかる時間", "kırma süresi"],
  "pin.digits": ["cifre", "digits", "位", "अंक", "dígitos", "dígitos", "أرقام", "chiffres", "цифр", "Ziffern", "桁", "hane"],
  "pin.recommended": ["consigliato: 8+", "recommended: 8+", "建议：8 位以上", "सलाह: 8+", "recomendado: 8+", "recomendado: 8+", "المستحسن: 8+", "recommandé : 8+", "рекомендуется: 8+", "empfohlen: 8+", "推奨：8 桁以上", "önerilen: 8+"],
  "pin.measured": ["Misurato: 353 ms per tentativo su un core (PBKDF2-HMAC-SHA512, 600.000 iterazioni).", "Measured: 353 ms per attempt on one core (PBKDF2-HMAC-SHA512, 600,000 iterations).", "实测：单核每次尝试 353 毫秒（PBKDF2-HMAC-SHA512，600,000 次迭代）。", "मापा गया: एक कोर पर प्रति प्रयास 353 ms (PBKDF2-HMAC-SHA512, 6,00,000 पुनरावृत्तियाँ)।", "Medido: 353 ms por intento en un núcleo (PBKDF2-HMAC-SHA512, 600.000 iteraciones).", "Medido: 353 ms por tentativa em um núcleo (PBKDF2-HMAC-SHA512, 600.000 iterações).", "مقيس: 353 ملّي ثانية لكل محاولة على نواة واحدة (PBKDF2-HMAC-SHA512، 600000 تكرار).", "Mesuré : 353 ms par tentative sur un cœur (PBKDF2-HMAC-SHA512, 600 000 itérations).", "Измерено: 353 мс на попытку на одном ядре (PBKDF2-HMAC-SHA512, 600 000 итераций).", "Gemessen: 353 ms pro Versuch auf einem Kern (PBKDF2-HMAC-SHA512, 600.000 Iterationen).", "実測：1 コアで 1 回あたり 353 ms（PBKDF2-HMAC-SHA512、600,000 回反復）。", "Ölçüldü: bir çekirdekte deneme başına 353 ms (PBKDF2-HMAC-SHA512, 600.000 tur)."],
  "pin.instant": ["istantaneo", "instant", "瞬间", "तुरंत", "instantáneo", "instantâneo", "فوري", "instantané", "мгновенно", "sofort", "一瞬", "anında"],
  "pin.underSecond": ["meno di un secondo", "under a second", "不到一秒", "एक सेकंड से कम", "menos de un segundo", "menos de um segundo", "أقل من ثانية", "moins d'une seconde", "меньше секунды", "unter einer Sekunde", "1 秒未満", "bir saniyeden az"],
  "pin.overMillion": ["oltre un milione di ", "over a million ", "超过一百万 ", "दस लाख से अधिक ", "más de un millón de ", "mais de um milhão de ", "أكثر من مليون ", "plus d'un million de ", "более миллиона ", "über eine Million ", "100 万を超える ", "bir milyondan fazla "],
  "pin.lab": ["laboratorio · 10.000×", "lab · 10,000×", "实验室 · 10,000×", "प्रयोगशाला · 10,000×", "laboratorio · 10.000×", "laboratório · 10.000×", "مختبر · 10000×", "laboratoire · 10 000×", "лаборатория · 10 000×", "Labor · 10.000×", "ラボ · 10,000×", "laboratuvar · 10.000×"],
  "pin.u.year": ["anno", "year", "年", "साल", "año", "ano", "سنة", "an", "год", "Jahr", "年", "yıl"],
  "pin.u.years": ["anni", "years", "年", "साल", "años", "anos", "سنة", "ans", "лет", "Jahre", "年", "yıl"],
  "pin.u.month": ["mese", "month", "个月", "महीना", "mes", "mês", "شهر", "mois", "месяц", "Monat", "か月", "ay"],
  "pin.u.months": ["mesi", "months", "个月", "महीने", "meses", "meses", "شهر", "mois", "месяцев", "Monate", "か月", "ay"],
  "pin.u.day": ["giorno", "day", "天", "दिन", "día", "dia", "يوم", "jour", "день", "Tag", "日", "gün"],
  "pin.u.days": ["giorni", "days", "天", "दिन", "días", "dias", "يوم", "jours", "дней", "Tage", "日", "gün"],
  "pin.u.hour": ["ora", "hour", "小时", "घंटा", "hora", "hora", "ساعة", "heure", "час", "Stunde", "時間", "saat"],
  "pin.u.hours": ["ore", "hours", "小时", "घंटे", "horas", "horas", "ساعة", "heures", "часов", "Stunden", "時間", "saat"],
  "pin.u.minute": ["minuto", "minute", "分钟", "मिनट", "minuto", "minuto", "دقيقة", "minute", "минута", "Minute", "分", "dakika"],
  "pin.u.minutes": ["minuti", "minutes", "分钟", "मिनट", "minutos", "minutos", "دقيقة", "minutes", "минут", "Minuten", "分", "dakika"],
  "pin.u.second": ["secondo", "second", "秒", "सेकंड", "segundo", "segundo", "ثانية", "seconde", "секунда", "Sekunde", "秒", "saniye"],
  "pin.u.seconds": ["secondi", "seconds", "秒", "सेकंड", "segundos", "segundos", "ثانية", "secondes", "секунд", "Sekunden", "秒", "saniye"],
  "pin.v.short": ["Troppo corto", "Too short", "太短", "बहुत छोटा", "Demasiado corto", "Curto demais", "قصير جدًا", "Trop court", "Слишком короткий", "Zu kurz", "短すぎます", "Çok kısa"],
  "pin.v.short2": ["Sotto le 4 cifre non c'è nulla da calcolare.", "Below 4 digits there is nothing to compute.", "少于 4 位就无需计算了。", "4 अंक से कम पर गिनने को कुछ नहीं है।", "Por debajo de 4 dígitos no hay nada que calcular.", "Abaixo de 4 dígitos não há nada a calcular.", "أقل من 4 أرقام لا يحتاج إلى حساب.", "En dessous de 4 chiffres, il n'y a rien à calculer.", "Меньше 4 цифр считать нечего.", "Unter 4 Ziffern gibt es nichts zu rechnen.", "4 桁未満では計算する価値もありません。", "4 haneden azında hesaplanacak bir şey yok."],
  "pin.v.weak": ["Non regge", "Does not hold", "撑不住", "टिकता नहीं", "No aguanta", "Não resiste", "لا يصمد", "Ne tient pas", "Не держит", "Hält nicht", "もちません", "Dayanmaz"],
  "pin.v.weak2": ["Un solo core lo apre in poche ore. Non usare questo PIN.", "A single core opens it in a few hours. Do not use this PIN.", "单核几小时就能打开。不要用这个 PIN。", "एक ही कोर कुछ घंटों में खोल देगा। यह PIN न रखें।", "Un solo núcleo lo abre en pocas horas. No uses este PIN.", "Um único núcleo abre em poucas horas. Não use este PIN.", "نواة واحدة تفتحه في ساعات. لا تستخدم هذا الرقم.", "Un seul cœur l'ouvre en quelques heures. N'utilisez pas ce PIN.", "Одно ядро вскроет его за часы. Не используйте этот PIN.", "Ein einzelner Kern öffnet ihn in wenigen Stunden. Nutze diese PIN nicht.", "1 コアで数時間で開きます。この PIN は使わないでください。", "Tek çekirdek birkaç saatte açar. Bu PIN'i kullanma."],
  "pin.v.fair": ["Regge un curioso, non un laboratorio", "Holds off a curious person, not a lab", "挡得住好奇的人，挡不住实验室", "जिज्ञासु को रोकेगा, प्रयोगशाला को नहीं", "Aguanta a un curioso, no a un laboratorio", "Segura um curioso, não um laboratório", "يصمد أمام فضولي، لا أمام مختبر", "Résiste à un curieux, pas à un laboratoire", "Остановит любопытного, но не лабораторию", "Hält Neugierige ab, kein Labor", "好奇心には勝てても、ラボには勝てません", "Meraklıyı durdurur, laboratuvarı durdurmaz"],
  "pin.v.fair2": ["Sei cifre cadono in un'ora e mezza su 64 core. Aggiungine due.", "Six digits fall in an hour and a half on 64 cores. Add two.", "6 位在 64 核上一个半小时就破。再加两位。", "6 अंक 64 कोर पर डेढ़ घंटे में गिर जाते हैं। दो अंक और जोड़ें।", "Seis dígitos caen en hora y media con 64 núcleos. Añade dos.", "Seis dígitos caem em uma hora e meia em 64 núcleos. Adicione dois.", "ستة أرقام تسقط في ساعة ونصف على 64 نواة. أضف رقمين.", "Six chiffres tombent en une heure et demie sur 64 cœurs. Ajoutez-en deux.", "Шесть цифр падают за полтора часа на 64 ядрах. Добавьте две.", "Sechs Ziffern fallen in eineinhalb Stunden auf 64 Kernen. Nimm zwei dazu.", "6 桁は 64 コアで 1 時間半で落ちます。2 桁足してください。", "Altı hane 64 çekirdekte bir buçuk saatte düşer. İki hane ekle."],
  "pin.v.good": ["Buono", "Good", "不错", "अच्छा", "Bueno", "Bom", "جيد", "Bon", "Хорошо", "Gut", "良好", "İyi"],
  "pin.v.good2": ["Da otto cifre il conto dell'attaccante cambia ordine di grandezza.", "From eight digits the attacker's arithmetic changes order of magnitude.", "从 8 位起，攻击者的算术差了一个数量级。", "8 अंक से हमलावर का हिसाब एक क्रम बड़ा हो जाता है।", "A partir de ocho dígitos la cuenta del atacante cambia de orden de magnitud.", "A partir de oito dígitos a conta do atacante muda de ordem de grandeza.", "من ثمانية أرقام يتغيّر حساب المهاجم بمرتبة كاملة.", "À partir de huit chiffres, le calcul de l'attaquant change d'ordre de grandeur.", "С восьми цифр расчёт атакующего меняет порядок величины.", "Ab acht Ziffern ändert sich die Rechnung des Angreifers um eine Größenordnung.", "8 桁からは攻撃側の計算量が桁違いになります。", "Sekiz haneden itibaren saldırganın hesabı bir büyüklük mertebesi değişir."],
  "pin.v.strong": ["Solido", "Solid", "稳固", "मज़बूत", "Sólido", "Sólido", "متين", "Solide", "Надёжно", "Solide", "堅牢", "Sağlam"],
  "pin.v.strong2": ["Dieci cifre o più: il PIN smette di essere l'anello debole.", "Ten digits or more: the PIN stops being the weak link.", "10 位以上：PIN 不再是最弱的一环。", "10 या अधिक अंक: PIN अब कमज़ोर कड़ी नहीं है।", "Diez dígitos o más: el PIN deja de ser el eslabón débil.", "Dez dígitos ou mais: o PIN deixa de ser o elo fraco.", "عشرة أرقام أو أكثر: لم يبق الرقم السري الحلقة الأضعف.", "Dix chiffres ou plus : le PIN cesse d'être le point faible.", "Десять цифр и больше: PIN перестаёт быть слабым звеном.", "Zehn Ziffern oder mehr: die PIN ist nicht mehr das schwache Glied.", "10 桁以上なら、PIN は弱点ではなくなります。", "On hane veya daha fazlası: PIN artık zayıf halka değil."],
};

export const UI12 = (() => {
  const out = {};
  for (let i = 0; i < L.length; i++) {
    const pack = {};
    for (const key of Object.keys(K)) pack[key] = K[key][i] || K[key][0];
    out[L[i]] = pack;
  }
  return out;
})();
